on:
  push:
  workflow_dispatch: {}

jobs:
  foo:
    runs-on: ubuntu-machined
    strategy:
      matrix:
        foo: [bar, baz, qoux]
        a: [b, c, d]
    steps:
      - run: "echo 'hello world'"
    